## Numpy array operations

In [1]:
import numpy as np

# slicing 

In [ ]:
array_1= np.array([12, 34, 10, 6, 40, 17, 2, 28])
print("basic slicing with step:", array_1[1:6:2])
print("slicing with negative index",array_1[-3])

basic slicing with step: [34  6 17]
slicing with negative index 17


In [14]:
array_2=np.array([[77, 12, 9],
    [4, 1, 5],
    [6, 8, 3]])
print("specific element", array_2[1,2])
print("entire row\n", array_2[1])
print("entire column\n", array_2[:,1])

specific element 5
entire row
 [4 1 5]
entire column
 [12  1  8]


# sorting

In [18]:
print("sorted array:\n", np.sort(array_1))
print("sorted 2D array:\n", np.sort(array_2))
print("sorted 2D array by row:\n", np.sort(array_2, axis=0))

sorted array:
 [ 2  6 10 12 17 28 34 40]
sorted 2D array:
 [[ 9 12 77]
 [ 1  4  5]
 [ 3  6  8]]
sorted 2D array by row:
 [[ 4  1  3]
 [ 6  8  5]
 [77 12  9]]


# Filter

In [20]:
array_3= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
filtered_arr = array_3[array_3 % 2 == 0]
# filter_arr will be: [False, True, False, True, False, True, False, True, False, True]
print("even numbers:\n", filtered_arr)

even numbers:
 [ 2  4  6  8 10]


# Indexing & np.where() function

In [24]:
indices= [0,2,4]
print(array_3[indices])

where_function= np.where(array_3>5)
print(where_function)
print(array_3[where_function])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
[ 6  7  8  9 10]


In [31]:
conditioned1=np.where(array_3>5, "true", "false")
conditioned2=np.where(array_3>5, 0, array_3)
conditioned3=np.where(array_3>5, "numpy", "false")

print(conditioned1)
print(conditioned2)
print(conditioned3)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']
[1 2 3 4 5 0 0 0 0 0]
['false' 'false' 'false' 'false' 'false' 'numpy' 'numpy' 'numpy' 'numpy'
 'numpy']


# adding and removing data

In [52]:
# A 2D list representing student grades in a table (rows, columns)
grade_1= np.array([
    [80, 75, 90],  # Row 0: Grades for student 1 (e.g., Math, Science, History)
    [65, 88, 72]   # Row 1: Grades for student 2
])
grade_2=np.array([
    [92, 79, 85]  # Row 0: Grades for student 3
])

combined_array= np.concatenate((grade_1,grade_2), axis=0)
print("added array: \n", combined_array)

print("equality check method 1:\n", grade_1==grade_2)
print("equality check method 2:\n", np.array_equal(grade_1,grade_2))

print("compatibility check for dimension/shape:\n", grade_1.shape == grade_2.shape)


withnewrow= np.vstack((grade_1,grade_2))
print(withnewrow)

grade_3= np.array([
    [80],
    [65]])
withnewcol= np.hstack((grade_1,grade_3))
print('\n', withnewcol)

print("deletion number be 80 at index 0")
print("deleted array", np.delete(grade_1,0))

added array: 
 [[80 75 90]
 [65 88 72]
 [92 79 85]]
equality check method 1:
 [[False False False]
 [False False False]]
equality check method 2:
 False
compatibility check for dimension/shape:
 False
[[80 75 90]
 [65 88 72]
 [92 79 85]]

 [[80 75 90 80]
 [65 88 72 65]]
deletion number be 80 at index 0
deleted array [75 90 65 88 72]
